configuration:
  projectName: commodity-service
server:
  port: 8080

---
spring:
  profiles: development
      datasource:
      url: jdbc:mysql://mysql:3306/sampledb
      username: root
      password: sa
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9000