configuration:
  projectName: config-server-demo
server:
  port: 8888

---

spring:
 profiles: development
 datasource:  
  driver-class-name: org.h2.Driver
 jpa:  
  hibernate:
   ddl-auto: update
server:
  port: 9014