configuration:
  projectName: commodity-service
server:
  port: 8080

---
spring:
  profiles: development
spring:
  thymeleaf:
  cache: false
# Database
db:
 driver: com.mysql.jdbc.Driver
 url: jdbc:mysql://localhost:3306/sakila
 username: root
 password: password
# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl: 
   auto: create
entitymanager :
  packagesToScan: netgloo
server:
  port: 9000