configuration:
  projectName: commodity-service
server:
  port: 8080

---
spring:
  profiles: development
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql:3306/sampledb
  username: root
  password: sa
  show_sql: false
  ddl-auto: none
server:
  port: 9000
